const ApiRouter = {
    LOGIN: "auth/login",
    PROFILE: "auth/profile",
    CUSTOMERS: "customers",
    USERS:"users",
    ZIPPERS: "zippers",
    FABRICS: "fabrics",
    THREADS: "threads",
    BUTTONS: "buttons",
    ACCESSORIES: "accessories",
    VELCRO: "velcro",
    MATERIALS: "materials",
    MATERIALS_CONSUPTIONS: "material-consumptions",
    TEMPLATES: "templates",
    TEMPLATE_ITEMS: "template-items",
    ORDERS: "orders",
    ORDER_MATERIALS: "order-materials",
    JOURNAL: "journal",
    PHOTOS: "photos",
    ORDER_STAFFS: "order-staffs",
    ZIPPERS_INVOICE: "zipper-invoices",
    FABRICS_INVOICE: "fabric-invoices",
    THREADS_INVOICE: "thread-invoices",
    BUTTONS_INVOICE: "button-invoices",
    ACCESSORIES_INVOICE: "accessories-invoices",
    VELCRO_INVOICE: "velcro-invoices",
}
export default ApiRouter